name: firt-web-app build and deploy to remote Wildfly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - users: actions/checkout@2

      - name: Set up JDK 11
        uses: actions/setup-java@1
        with:
          java-version: 11

      - name: Build with maven
        id: mvn_build
        run: |
          mvn --batch-mode clean install wildfly:deploy -Dwildfly.hostname=${{ WILDFLY_HOSTNAME }} \
          -Dwildfly.username=${{ secrets.WILDFLY_ADMIN_LOGIN }} \
          -Dwildfly.password=${{ secrets.WILDFLY_ADMIN_PASSWORD }}